// ==================================================
// 02_Make_Masks_From_Z_Projects_WORKING.ijm
// ==================================================
//
// PURPOSE:
// This macro creates binary masks from the 8-bit Z-projection images
// generated by the preprocessing macro.
//
// This macro does NOT quantify particles.
// It only creates and saves binary masks.
//
// --------------------------------------------------
// INPUT FOLDERS:
// --------------------------------------------------
//
// Parent folder/
//      03_Z_Project_1_3_8bit/
//      04_Z_Project_4_6_8bit/
//      05_Z_Project_7_9_8bit/
//
// --------------------------------------------------
// OUTPUT FOLDER:
// --------------------------------------------------
//
// Parent folder/
//      06_Masks/
//          C2_Bassoon_1_3/
//          C2_Bassoon_4_6/
//          C2_Bassoon_7_9/
//          C3_Gephyrin_1_3/
//          C3_Gephyrin_4_6/
//          C3_Gephyrin_7_9/
//          C4_PSD95_1_3/
//          C4_PSD95_4_6/
//          C4_PSD95_7_9/
//
// --------------------------------------------------
// THRESHOLD PARAMETERS:
// --------------------------------------------------
//
// C2 Bassoon:
//      Auto Threshold = Triangle
//
// C3 Gephyrin:
//      Auto Threshold = Moments
//
// C4 PSD95:
//      Auto Threshold = Triangle
//
// Common Auto Threshold settings:
//      Ignore black = yes
//      White objects on black background = yes
//
// ==================================================

requires("1.53");

macro "02 Make Masks From Z Projects" {

    // --------------------------------------------------
    // Choose main parent folder
    // --------------------------------------------------

    args = split(getArgument(), ";");
    filePath = args[0];
    parentDir = args[1];

    if (!endsWith(parentDir, "/")) {
        parentDir = parentDir + "/";
    }

    if (nImages == 0) {
        if (filePath == "") {
            exit("ERROR: No image open and no path argument provided.");
        }
        open(filePath);
    }

    logFile = parentDir + "debug_log.txt";

    // --------------------------------------------------
    // Define input folders
    // --------------------------------------------------

    dirZ13 = parentDir + "03_Z_Project_1_3_8bit/";
    dirZ46 = parentDir + "04_Z_Project_4_6_8bit/";
    dirZ79 = parentDir + "05_Z_Project_7_9_8bit/";

    // --------------------------------------------------
    // Check input folders
    // --------------------------------------------------

    if (!File.exists(dirZ13)) {
        exit("ERROR: Missing input folder:\n" + dirZ13);
    }

    if (!File.exists(dirZ46)) {
        exit("ERROR: Missing input folder:\n" + dirZ46);
    }

    if (!File.exists(dirZ79)) {
        exit("ERROR: Missing input folder:\n" + dirZ79);
    }

    // --------------------------------------------------
    // Define output folders
    // --------------------------------------------------

    dirMasks = parentDir + "06_Masks/";

    dirC2_13 = dirMasks + "C2_Bassoon_1_3/";
    dirC2_46 = dirMasks + "C2_Bassoon_4_6/";
    dirC2_79 = dirMasks + "C2_Bassoon_7_9/";

    dirC3_13 = dirMasks + "C3_Gephyrin_1_3/";
    dirC3_46 = dirMasks + "C3_Gephyrin_4_6/";
    dirC3_79 = dirMasks + "C3_Gephyrin_7_9/";

    dirC4_13 = dirMasks + "C4_PSD95_1_3/";
    dirC4_46 = dirMasks + "C4_PSD95_4_6/";
    dirC4_79 = dirMasks + "C4_PSD95_7_9/";

    File.makeDirectory(dirMasks);

    File.makeDirectory(dirC2_13);
    File.makeDirectory(dirC2_46);
    File.makeDirectory(dirC2_79);

    File.makeDirectory(dirC3_13);
    File.makeDirectory(dirC3_46);
    File.makeDirectory(dirC3_79);

    File.makeDirectory(dirC4_13);
    File.makeDirectory(dirC4_46);
    File.makeDirectory(dirC4_79);

    print("----------------------------------------");
    print("Starting mask generation.");
    print("Parent folder: " + parentDir);

    // --------------------------------------------------
    // Set default threshold methods per marker
    // --------------------------------------------------

    methodBassoon  = "Triangle";
    methodGephyrin = "Moments";
    methodPSD95    = "Triangle";

    // --------------------------------------------------
    // Threshold method options for dialog
    // --------------------------------------------------

    methods = newArray("Triangle", "Moments", "Huang", "Otsu", "Default",
                       "Li", "MaxEntropy", "Mean", "MinError(I)", "Minimum",
                       "Percentile", "RenyiEntropy", "Shanbhag", "Yen",
                       "Intermodes", "IsoData");

    // --------------------------------------------------
    // Main loop — generate masks, inspect, re-run if needed
    // --------------------------------------------------

    do {

        setBatchMode(true);

        // process each Z projection folder with current methods
        processZFolder(dirZ13, "1_3", dirC2_13, dirC3_13, dirC4_13, methodBassoon, methodGephyrin, methodPSD95);
        processZFolder(dirZ46, "4_6", dirC2_46, dirC3_46, dirC4_46, methodBassoon, methodGephyrin, methodPSD95);
        processZFolder(dirZ79, "7_9", dirC2_79, dirC3_79, dirC4_79, methodBassoon, methodGephyrin, methodPSD95);

        setBatchMode(false);

        // --------------------------------------------------
        // Open one example mask per channel for inspection
        // --------------------------------------------------

        openFirstMask(dirC2_13, "Bassoon 1-3");
        openFirstMask(dirC3_13, "Gephyrin 1-3");
        openFirstMask(dirC4_13, "PSD95 1-3");

        // --------------------------------------------------
        // Ask user to inspect and optionally re-run
        // --------------------------------------------------

        Dialog.create("Inspect Masks");
        Dialog.addMessage(
            "Inspect the masks for Bassoon, Gephyrin, and PSD95.\n\n" +
            "If the masks look correct, click OK to continue.\n" +
            "To retry with different threshold methods, change the\n" +
            "selections below and check 'Re-run with new settings'."
        );
        Dialog.addChoice("Bassoon (C2) method:",  methods, methodBassoon);
        Dialog.addChoice("Gephyrin (C3) method:", methods, methodGephyrin);
        Dialog.addChoice("PSD95 (C4) method:",    methods, methodPSD95);
        Dialog.addCheckbox("Re-run with new settings", false);
        Dialog.show();

        methodBassoon  = Dialog.getChoice();
        methodGephyrin = Dialog.getChoice();
        methodPSD95    = Dialog.getChoice();
        rerun          = Dialog.getCheckbox();

        // close inspection images before next iteration or continuing
        run("Close All");

    } while (rerun);

    print("----------------------------------------");
    print("DONE.");
    print("Masks saved in:");
    print(dirMasks);

    run("Quit");
}


// ==================================================
// FUNCTION: openFirstMask
// ==================================================

function openFirstMask(maskDir, label) {
    if (!File.exists(maskDir)) {
        print("WARNING: Could not open masks for inspection - folder not found: " + maskDir);
        return;
    }

    fileList = getFileList(maskDir);

    for (i = 0; i < fileList.length; i++) {
        if (endsWith(fileList[i], ".tif") || endsWith(fileList[i], ".tiff")) {
            open(maskDir + fileList[i]);
            rename(label + " - " + fileList[i]);
            return; // only open the first one
        }
    }

    print("WARNING: No .tif files found in: " + maskDir);
}


// ==================================================
// FUNCTION: processZFolder
// ==================================================
//
// Processes one Z-projection folder.
// It identifies the channel/marker from the filename.
//
// Expected filenames contain:
//      _C2_Bassoon_
//      _C3_Gephyrin_
//      _C4_PSD95_
//
// C1 DAPI is skipped.
//
// ==================================================

function processZFolder(inputDir, zLabel, outC2, outC3, outC4, methodBassoon, methodGephyrin, methodPSD95) {

    fileList = getFileList(inputDir);

    print("----------------------------------------");
    print("Processing Z group: " + zLabel);
    print("Input folder: " + inputDir);

    for (i = 0; i < fileList.length; i++) {

        fileName = fileList[i];

        if (endsWith(fileName, ".tif") || endsWith(fileName, ".tiff")) {

            // Skip DAPI
            if (indexOf(fileName, "_C1_DAPI_") >= 0) {
                print("Skipping DAPI file: " + fileName);
                continue;
            }

            // C2 Bassoon
            if (indexOf(fileName, "_C2_Bassoon_") >= 0) {
                makeMask(inputDir, fileName, methodBassoon, outC2);
                continue;
            }

            // C3 Gephyrin
            if (indexOf(fileName, "_C3_Gephyrin_") >= 0) {
                makeMask(inputDir, fileName, methodGephyrin, outC3);
                continue;
            }

            // C4 PSD95
            if (indexOf(fileName, "_C4_PSD95_") >= 0) {
                makeMask(inputDir, fileName, methodPSD95, outC4);
                continue;
            }

            print("WARNING: File did not match C2/C3/C4 naming pattern: " + fileName);
        }
    }
}


// ==================================================
// FUNCTION: makeMask
// ==================================================
//
// Opens one 8-bit Z-projection image.
// Applies marker-specific Auto Threshold.
// Converts the thresholded image to a binary mask.
// Saves the mask.
//
// Output filename:
//      original_filename_MASK.tif
//
// ==================================================

function makeMask(inputDir, fileName, thresholdMethod, outputDir) {

    open(inputDir + fileName);

    baseName = removeExtension(fileName);

    print("Creating mask: " + fileName + " using " + thresholdMethod);

    // Make sure the image is 8-bit
    run("8-bit");

    // Clear active selection
    run("Select None");

    // Set black background option before mask conversion
    setOption("BlackBackground", true);

    // Apply Auto Threshold using the settings tested manually:
    // ignore_black = ignore zero-value background
    // white = white objects on black background
    run("Auto Threshold", "method=" + thresholdMethod + " ignore_black white");

    // Convert thresholded image to binary mask
    run("Convert to Mask");

    // Save mask
    saveAs("Tiff", outputDir + baseName + "_MASK.tif");

    close();
}


// ==================================================
// FUNCTION: removeExtension
// ==================================================

function removeExtension(name) {
    dot = lastIndexOf(name, ".");

    if (dot == -1) {
        return name;
    } else {
        return substring(name, 0, dot);
    }
}