// ==================================================
// 02_Make_Masks_From_Z_Projects_WORKING.ijm
// ==================================================
//
// PURPOSE:
// This macro creates binary masks from the 8-bit Z-projection images
// generated by the preprocessing macro.
//
// This macro does NOT quantify particles.
// It only creates and saves binary masks.
//
// --------------------------------------------------
// INPUT FOLDERS:
// --------------------------------------------------
//
// Parent folder/
//      03_Z_Project_1_3_8bit/
//      04_Z_Project_4_6_8bit/
//      05_Z_Project_7_9_8bit/
//
// --------------------------------------------------
// OUTPUT FOLDER:
// --------------------------------------------------
//
// Parent folder/
//      06_Masks/
//          C2_Bassoon_1_3/
//          C2_Bassoon_4_6/
//          C2_Bassoon_7_9/
//          C3_Gephyrin_1_3/
//          C3_Gephyrin_4_6/
//          C3_Gephyrin_7_9/
//          C4_PSD95_1_3/
//          C4_PSD95_4_6/
//          C4_PSD95_7_9/
//
// --------------------------------------------------
// THRESHOLD PARAMETERS:
// --------------------------------------------------
//
// C2 Bassoon:
//      Auto Threshold = Triangle
//
// C3 Gephyrin:
//      Auto Threshold = Moments
//
// C4 PSD95:
//      Auto Threshold = Triangle
//
// Common Auto Threshold settings:
//      Ignore black = yes
//      White objects on black background = yes
//
// ==================================================

requires("1.53");

macro "02 Make Masks From Z Projects" {

    // --------------------------------------------------
    // Choose main parent folder
    // --------------------------------------------------

    args = split(getArgument(), ";");
    filePath = args[0];
    parentDir = args[1];

    if (!endsWith(parentDir, "/")) {
        parentDir = parentDir + "/";
    }

    if (nImages == 0) {
        if (filePath == "") {
            exit("ERROR: No image open and no path argument provided.");
        }
        open(filePath);
    }

    logFile = parentDir + "debug_log.txt";

    // debug log
    //File.saveString("filePath: " + filePath + "\nparentDir: " + parentDir, logFile);

    
    // --------------------------------------------------
    // Define input folders
    // --------------------------------------------------

    dirZ13 = parentDir + "03_Z_Project_1_3_8bit/";
    dirZ46 = parentDir + "04_Z_Project_4_6_8bit/";
    dirZ79 = parentDir + "05_Z_Project_7_9_8bit/";

    // --------------------------------------------------
    // Check input folders
    // --------------------------------------------------

    if (!File.exists(dirZ13)) {
        exit("ERROR: Missing input folder:\n" + dirZ13);
    }

    if (!File.exists(dirZ46)) {
        exit("ERROR: Missing input folder:\n" + dirZ46);
    }

    if (!File.exists(dirZ79)) {
        exit("ERROR: Missing input folder:\n" + dirZ79);
    }

    // --------------------------------------------------
    // Define output folders
    // --------------------------------------------------

    dirMasks = parentDir + "06_Masks/";

    dirC2_13 = dirMasks + "C2_Bassoon_1_3/";
    dirC2_46 = dirMasks + "C2_Bassoon_4_6/";
    dirC2_79 = dirMasks + "C2_Bassoon_7_9/";

    dirC3_13 = dirMasks + "C3_Gephyrin_1_3/";
    dirC3_46 = dirMasks + "C3_Gephyrin_4_6/";
    dirC3_79 = dirMasks + "C3_Gephyrin_7_9/";

    dirC4_13 = dirMasks + "C4_PSD95_1_3/";
    dirC4_46 = dirMasks + "C4_PSD95_4_6/";
    dirC4_79 = dirMasks + "C4_PSD95_7_9/";

    File.makeDirectory(dirMasks);

    File.makeDirectory(dirC2_13);
    File.makeDirectory(dirC2_46);
    File.makeDirectory(dirC2_79);

    File.makeDirectory(dirC3_13);
    File.makeDirectory(dirC3_46);
    File.makeDirectory(dirC3_79);

    File.makeDirectory(dirC4_13);
    File.makeDirectory(dirC4_46);
    File.makeDirectory(dirC4_79);

    print("----------------------------------------");
    print("Starting mask generation.");
    print("Parent folder: " + parentDir);

    setBatchMode(true);

    // --------------------------------------------------
    // Process each Z projection folder
    // --------------------------------------------------

    processZFolder(dirZ13, "1_3", dirC2_13, dirC3_13, dirC4_13);
    processZFolder(dirZ46, "4_6", dirC2_46, dirC3_46, dirC4_46);
    processZFolder(dirZ79, "7_9", dirC2_79, dirC3_79, dirC4_79);

    setBatchMode(false);

    // --------------------------------------------------
    // Open masks for visual inspection
    // --------------------------------------------------

    // open one example mask from each channel/z-group for inspection
    openFirstMask(dirC2_13, "Bassoon 1-3");
    openFirstMask(dirC3_13, "Gephyrin 1-3");
    openFirstMask(dirC4_13, "PSD95 1-3");

    // pause and wait for user to inspect and approve
    waitForUser("Inspect Masks", 
        "Check the masks for Bassoon, Gephyrin, and PSD95.\n\n" +
        "When you are happy with the masks, click OK to continue.");

    // close all open mask images before continuing
    run("Close All");

    print("----------------------------------------");
    print("DONE.");
    print("Masks saved in:");
    print(dirMasks);
    run("Quit")
}


// ==================================================
// FUNCTION: openFirstMask
// ==================================================

function openFirstMask(maskDir, label) {
    if (!File.exists(maskDir)) {
        print("WARNING: Could not open masks for inspection - folder not found: " + maskDir);
        return;
    }

    fileList = getFileList(maskDir);

    for (i = 0; i < fileList.length; i++) {
        if (endsWith(fileList[i], ".tif") || endsWith(fileList[i], ".tiff")) {
            open(maskDir + fileList[i]);
            rename(label + " - " + fileList[i]);
            return; // only open the first one
        }
    }

    print("WARNING: No .tif files found in: " + maskDir);
}


// ==================================================
// FUNCTION: processZFolder
// ==================================================
//
// Processes one Z-projection folder.
// It identifies the channel/marker from the filename.
//
// Expected filenames contain:
//      _C2_Bassoon_
//      _C3_Gephyrin_
//      _C4_PSD95_
//
// C1 DAPI is skipped.
//
// ==================================================

function processZFolder(inputDir, zLabel, outC2, outC3, outC4) {

    fileList = getFileList(inputDir);

    print("----------------------------------------");
    print("Processing Z group: " + zLabel);
    print("Input folder: " + inputDir);

    for (i = 0; i < fileList.length; i++) {

        fileName = fileList[i];

        if (endsWith(fileName, ".tif") || endsWith(fileName, ".tiff")) {

            // Skip DAPI
            if (indexOf(fileName, "_C1_DAPI_") >= 0) {
                print("Skipping DAPI file: " + fileName);
                continue;
            }

            // C2 Bassoon
            if (indexOf(fileName, "_C2_Bassoon_") >= 0) {
                makeMask(inputDir, fileName, "Triangle", outC2);
                continue;
            }

            // C3 Gephyrin
            if (indexOf(fileName, "_C3_Gephyrin_") >= 0) {
                makeMask(inputDir, fileName, "Moments", outC3);
                continue;
            }

            // C4 PSD95
            if (indexOf(fileName, "_C4_PSD95_") >= 0) {
                makeMask(inputDir, fileName, "Triangle", outC4);
                continue;
            }

            print("WARNING: File did not match C2/C3/C4 naming pattern: " + fileName);
        }
    }
}


// ==================================================
// FUNCTION: makeMask
// ==================================================
//
// Opens one 8-bit Z-projection image.
// Applies marker-specific Auto Threshold.
// Converts the thresholded image to a binary mask.
// Saves the mask.
//
// Output filename:
//      original_filename_MASK.tif
//
// ==================================================

function makeMask(inputDir, fileName, thresholdMethod, outputDir) {

    open(inputDir + fileName);

    baseName = removeExtension(fileName);

    print("Creating mask: " + fileName + " using " + thresholdMethod);

    // Make sure the image is 8-bit
    run("8-bit");

    // Clear active selection
    run("Select None");

    // Set black background option before mask conversion
    setOption("BlackBackground", true);

    // Apply Auto Threshold using the settings tested manually:
    // ignore_black = ignore zero-value background
    // white = white objects on black background
    run("Auto Threshold", "method=" + thresholdMethod + " ignore_black white");

    // Convert thresholded image to binary mask
    run("Convert to Mask");

    // Save mask
    saveAs("Tiff", outputDir + baseName + "_MASK.tif");

    close();
}


// ==================================================
// FUNCTION: removeExtension
// ==================================================

function removeExtension(name) {
    dot = lastIndexOf(name, ".");

    if (dot == -1) {
        return name;
    } else {
        return substring(name, 0, dot);
    }
}