// ==================================================
// 03_Analyze_Individual_Marker_Puncta_WITH_LAYER_ROI_WORKING.ijm
// ==================================================
//
// PURPOSE:
// This macro analyzes individual synaptic-marker puncta from binary masks.
//
// It reads the masks generated by macro 02 and produces:
//      1. individual_puncta_coordinates.csv
//      2. marker_density_summary.csv
//      3. QC overlay images showing counted particles
//      4. ROI Manager .zip files
//
// --------------------------------------------------
// BIOLOGICAL DESIGN:
// --------------------------------------------------
//
// This version is designed for small homogeneous cortical ROIs.
// For example:
//      - L1 ROI
//      - L2/3 ROI
//
// The macro asks for:
//      Layer
//      ROI_ID
//
// These values are saved into the results tables so later you can group by:
//      L1 vs L2/3
//      ROI_01 vs ROI_02
//      marker
//      Z group
//
// --------------------------------------------------
// INPUT FOLDER:
// --------------------------------------------------
//
// Parent folder/
//      06_Masks/
//          C2_Bassoon_1_3/
//          C2_Bassoon_4_6/
//          C2_Bassoon_7_9/
//          C3_Gephyrin_1_3/
//          C3_Gephyrin_4_6/
//          C3_Gephyrin_7_9/
//          C4_PSD95_1_3/
//          C4_PSD95_4_6/
//          C4_PSD95_7_9/
//
// --------------------------------------------------
// OUTPUT FOLDER:
// --------------------------------------------------
//
// Parent folder/
//      07_Individual_Marker_Analysis/
//          01_Results/
//              individual_puncta_coordinates.csv
//              marker_density_summary.csv
//
//          02_QC_Overlays/
//              counted-particle overlay images
//
//          03_ROI_Sets/
//              ROI .zip files
//
// --------------------------------------------------
// PARTICLE PARAMETERS:
// --------------------------------------------------
//
// C2 Bassoon:
//      Size = 0.035-1.5 um^2
//
// C3 Gephyrin:
//      Size = 0.04-2.0 um^2
//
// C4 PSD95:
//      Size = 0.035-2.0 um^2
//
// Common settings:
//      Circularity = 0.00-1.00
//      Exclude particles touching image edges = yes
//
// --------------------------------------------------
// IMPORTANT CALIBRATION NOTE:
// --------------------------------------------------
//
// In this dataset, Fiji may report the calibration unit as "pixels"
// even though the pixel size value is biologically correct:
//
//      pixel width  = 0.1083
//      pixel height = 0.1083
//
// We interpret this as:
//
//      0.1083 um / pixel
//
// Therefore, this macro saves the output columns explicitly as:
//      Pixel_width_um
//      Pixel_height_um
//      ROI_width_um
//      ROI_height_um
//      ROI_area_um2
//
// --------------------------------------------------
// DENSITY CALCULATION:
// --------------------------------------------------
//
//      Density_per_um2 = Puncta_count / ROI_area_um2
//
//      Density_per_100um2 = Density_per_um2 * 100
//
// The denominator is the full X/Y area of the ROI image/mask.
// Because the masks were derived from the original ROI stack without resizing,
// this is the area of the selected ROI.
//
// --------------------------------------------------
// SPATIAL ANALYSIS NOTE:
// --------------------------------------------------
//
// The individual puncta table saves X/Y centroid coordinates for every punctum.
// This will allow later spatial analyses such as:
//
//      nearest-neighbor distance
//      Ripley's K/L
//      pair-correlation
//      DBSCAN clustering
//      cross-marker spatial association
//
// ==================================================

requires("1.53");

macro "03 Analyze Individual Marker Puncta With Layer ROI" {

    // --------------------------------------------------
    // Choose main parent folder
    // --------------------------------------------------

    args = split(getArgument(), ";");
    filePath = args[0];
    parentDir = args[1];
    layerName = args[2];
    roiID = args[3];
    regionName = args[4];

    if (!endsWith(parentDir, "/")) {
        parentDir = parentDir + "/";
    }

    if (nImages == 0) {
        if (filePath == "") {
            exit("ERROR: No image open and no path argument provided.");
        }
        open(filePath);
    }

    logFile = parentDir + "debug_log.txt";

    // debug log
    File.saveString("filePath: " + filePath + "\nparentDir: " + parentDir, logFile);

    // --------------------------------------------------
    // Ask for layer and ROI metadata
    // --------------------------------------------------

    // Clean metadata strings for filenames.
    layerSafe = replace(layerName, "/", "_");
    layerSafe = replace(layerSafe, " ", "_");

    roiSafe = replace(roiID, "/", "_");
    roiSafe = replace(roiSafe, " ", "_");

    regionSafe = replace(regionName, "/", "_");
    regionSafe = replace(regionSafe, " ", "_");

    // --------------------------------------------------
    // Define input and output folders
    // --------------------------------------------------

    dirMasks = parentDir + "06_Masks/";

    if (!File.exists(dirMasks)) {
        exit("ERROR: Missing mask folder:\n" + dirMasks);
    }

    dirAnalysis = parentDir + "07_Individual_Marker_Analysis/";
    dirResults = dirAnalysis + "01_Results/";
    dirOverlays = dirAnalysis + "02_QC_Overlays/";
    dirROIs = dirAnalysis + "03_ROI_Sets/";

    File.makeDirectory(dirAnalysis);
    File.makeDirectory(dirResults);
    File.makeDirectory(dirOverlays);
    File.makeDirectory(dirROIs);

    // --------------------------------------------------
    // Define output CSV files
    // --------------------------------------------------

    individualCSV = dirResults + "individual_puncta_coordinates.csv";
    summaryCSV = dirResults + "marker_density_summary.csv";

    // This macro overwrites previous CSV files in this folder.
    // That is intentional for one ROI folder.
    // If you re-run the macro, old results are replaced.

    individualHeader =
        "Image_ID,Region,Layer,ROI_ID,Channel,Marker,Z_group,Particle_ID," +
        "ROI_width_um,ROI_height_um,ROI_area_um2," +
        "Image_width_pixels,Image_height_pixels," +
        "Pixel_width_um,Pixel_height_um," +
        "X_centroid_um,Y_centroid_um," +
        "X_centroid_px,Y_centroid_px," +
        "Area_um2,Perimeter_um,Circularity,Feret_um,MinFeret_um," +
        "Size_filter_min_um2,Size_filter_max_um2," +
        "Mask_file\n";

    summaryHeader =
        "Image_ID,Region,Layer,ROI_ID,Channel,Marker,Z_group," +
        "ROI_width_um,ROI_height_um,ROI_area_um2," +
        "Image_width_pixels,Image_height_pixels," +
        "Pixel_width_um,Pixel_height_um," +
        "Puncta_count," +
        "Density_per_um2,Density_per_100um2," +
        "Total_puncta_area_um2,Percent_area_covered," +
        "Mean_puncta_area_um2,Min_puncta_area_um2,Max_puncta_area_um2," +
        "Size_filter_min_um2,Size_filter_max_um2," +
        "Mask_file\n";

    File.saveString(individualHeader, individualCSV);
    File.saveString(summaryHeader, summaryCSV);

    File.append("----------------------------------------", logFile);
    File.append("Starting macro 03: individual marker puncta analysis.", logFile);
    File.append("Parent folder: " + parentDir, logFile);
    File.append("Mask folder: " + dirMasks, logFile);
    File.append("Results folder: " + dirResults, logFile);
    File.append("Region: " + regionName, logFile);
    File.append("Layer: " + layerName, logFile);
    File.append("ROI_ID: " + roiID, logFile);

    setBatchMode(true);

    // --------------------------------------------------
    // Process each marker/Z-group folder
    // --------------------------------------------------

    processMaskFolder(dirMasks + "C2_Bassoon_1_3/",  "C2", "Bassoon",  "1_3", 0.035, 1.5,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C2_Bassoon_4_6/",  "C2", "Bassoon",  "4_6", 0.035, 1.5,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C2_Bassoon_7_9/",  "C2", "Bassoon",  "7_9", 0.035, 1.5,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C3_Gephyrin_1_3/", "C3", "Gephyrin", "1_3", 0.04, 2.0,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C3_Gephyrin_4_6/", "C3", "Gephyrin", "4_6", 0.04, 2.0,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C3_Gephyrin_7_9/", "C3", "Gephyrin", "7_9", 0.04, 2.0,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C4_PSD95_1_3/",    "C4", "PSD95",    "1_3", 0.035, 2.0,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C4_PSD95_4_6/",    "C4", "PSD95",    "4_6", 0.035, 2.0,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    processMaskFolder(dirMasks + "C4_PSD95_7_9/",    "C4", "PSD95",    "7_9", 0.035, 2.0,
                      individualCSV, summaryCSV, dirOverlays, dirROIs,
                      regionName, layerName, roiID, regionSafe, layerSafe, roiSafe);

    setBatchMode(false);

    File.append("----------------------------------------", logFile);
    File.append("DONE.", logFile);
    File.append("Individual puncta table:", logFile);
    File.append(individualCSV, logFile);
    File.append("Summary density table:", logFile);
    File.append(summaryCSV, logFile);
    File.append("QC overlays:", logFile);
    File.append(dirOverlays, logFile);
    File.append("ROI sets:", logFile);
    File.append(dirROIs, logFile);
}


// ==================================================
// FUNCTION: processMaskFolder
// ==================================================

function processMaskFolder(maskDir, channel, marker, zGroup, minSize, maxSize,
                           individualCSV, summaryCSV, dirOverlays, dirROIs,
                           regionName, layerName, roiID, regionSafe, layerSafe, roiSafe) {

    if (!File.exists(maskDir)) {
        File.append("WARNING: Mask folder not found. Skipping:", logFile);
        File.append(maskDir, logFile);
        return;
    }

    fileList = getFileList(maskDir);

    File.append("----------------------------------------", logFile);
    File.append("Processing: " + channel + " " + marker + " Z " + zGroup, logFile);
    File.append("Folder: " + maskDir, logFile);
    File.append("Particle size filter: " + minSize + "-" + maxSize + " um^2", logFile);

    for (i = 0; i < fileList.length; i++) {

        fileName = fileList[i];

        if (endsWith(fileName, ".tif") || endsWith(fileName, ".tiff")) {

            analyzeOneMask(maskDir, fileName, channel, marker, zGroup,
                           minSize, maxSize,
                           individualCSV, summaryCSV,
                           dirOverlays, dirROIs,
                           regionName, layerName, roiID,
                           regionSafe, layerSafe, roiSafe);
        }
    }
}


// ==================================================
// FUNCTION: analyzeOneMask
// ==================================================

function analyzeOneMask(maskDir, fileName, channel, marker, zGroup,
                        minSize, maxSize,
                        individualCSV, summaryCSV,
                        dirOverlays, dirROIs,
                        regionName, layerName, roiID,
                        regionSafe, layerSafe, roiSafe) {

    open(maskDir + fileName);

    maskTitle = getTitle();
    baseName = removeExtension(fileName);

    // Make sure image is 8-bit.
    run("8-bit");
    setOption("BlackBackground", true);
    run("Select None");

    // --------------------------------------------------
    // Calibration and ROI area
    // --------------------------------------------------

    getPixelSize(unit, pixelWidth, pixelHeight, voxelDepth);

    imageWidthPixels = getWidth();
    imageHeightPixels = getHeight();

    // The numeric calibration is treated as microns per pixel.
    pixelWidthUm = pixelWidth;
    pixelHeightUm = pixelHeight;

    ROI_width_um = imageWidthPixels * pixelWidthUm;
    ROI_height_um = imageHeightPixels * pixelHeightUm;
    ROI_area_um2 = ROI_width_um * ROI_height_um;

    imageID = getImageIDFromMaskName(baseName, channel, marker, zGroup);

    File.append("Analyzing: " + fileName, logFile);
    File.append("Image ID: " + imageID, logFile);
    File.append("Original Fiji unit label: " + unit, logFile);
    File.append("Pixel width used: " + pixelWidthUm + " um", logFile);
    File.append("Pixel height used: " + pixelHeightUm + " um", logFile);
    File.append("ROI size: " + ROI_width_um + " x " + ROI_height_um + " um", logFile);
    File.append("ROI area: " + ROI_area_um2 + " um^2", logFile);

    if (pixelWidthUm == 1 && pixelHeightUm == 1) {
        File.append("WARNING: Pixel size is 1 x 1. Check calibration before trusting density.", logFile);
    }

    // --------------------------------------------------
    // Set measurements
    // --------------------------------------------------

    run("Set Measurements...", "area centroid perimeter shape feret's redirect=None decimal=6");

    run("Clear Results");
    roiManager("Reset");

    // --------------------------------------------------
    // Analyze particles
    // --------------------------------------------------

    particleOptions =
        "size=" + minSize + "-" + maxSize +
        " circularity=0.00-1.00 show=Nothing display clear exclude add";

    run("Analyze Particles...", particleOptions);

    punctaCount = nResults();

    // --------------------------------------------------
    // Collect individual puncta values
    // --------------------------------------------------

    totalPunctaArea = 0;
    minPunctaArea = 0;
    maxPunctaArea = 0;

    for (r = 0; r < punctaCount; r++) {

        area_um2 = getResult("Area", r);
        x_um = getResult("X", r);
        y_um = getResult("Y", r);
        perimeter_um = getResult("Perim.", r);
        circularity = getResult("Circ.", r);
        feret_um = getResult("Feret", r);
        minFeret_um = getResult("MinFeret", r);

        x_px = x_um / pixelWidthUm;
        y_px = y_um / pixelHeightUm;

        totalPunctaArea = totalPunctaArea + area_um2;

        if (r == 0) {
            minPunctaArea = area_um2;
            maxPunctaArea = area_um2;
        } else {
            if (area_um2 < minPunctaArea) {
                minPunctaArea = area_um2;
            }
            if (area_um2 > maxPunctaArea) {
                maxPunctaArea = area_um2;
            }
        }

        particleID = r + 1;

        individualRow =
            imageID + "," +
            regionName + "," +
            layerName + "," +
            roiID + "," +
            channel + "," +
            marker + "," +
            zGroup + "," +
            particleID + "," +
            ROI_width_um + "," +
            ROI_height_um + "," +
            ROI_area_um2 + "," +
            imageWidthPixels + "," +
            imageHeightPixels + "," +
            pixelWidthUm + "," +
            pixelHeightUm + "," +
            x_um + "," +
            y_um + "," +
            x_px + "," +
            y_px + "," +
            area_um2 + "," +
            perimeter_um + "," +
            circularity + "," +
            feret_um + "," +
            minFeret_um + "," +
            minSize + "," +
            maxSize + "," +
            fileName + "\n";

        File.append(individualRow, individualCSV);
    }

    // --------------------------------------------------
    // Summary values
    // --------------------------------------------------

    if (punctaCount > 0) {
        meanPunctaArea = totalPunctaArea / punctaCount;
    } else {
        meanPunctaArea = 0;
        minPunctaArea = 0;
        maxPunctaArea = 0;
    }

    densityPerUm2 = punctaCount / ROI_area_um2;
    densityPer100Um2 = densityPerUm2 * 100;
    percentAreaCovered = (totalPunctaArea / ROI_area_um2) * 100;

    summaryRow =
        imageID + "," +
        regionName + "," +
        layerName + "," +
        roiID + "," +
        channel + "," +
        marker + "," +
        zGroup + "," +
        ROI_width_um + "," +
        ROI_height_um + "," +
        ROI_area_um2 + "," +
        imageWidthPixels + "," +
        imageHeightPixels + "," +
        pixelWidthUm + "," +
        pixelHeightUm + "," +
        punctaCount + "," +
        densityPerUm2 + "," +
        densityPer100Um2 + "," +
        totalPunctaArea + "," +
        percentAreaCovered + "," +
        meanPunctaArea + "," +
        minPunctaArea + "," +
        maxPunctaArea + "," +
        minSize + "," +
        maxSize + "," +
        fileName + "\n";

    File.append(summaryRow, summaryCSV);

    // --------------------------------------------------
    // Save ROI set
    // --------------------------------------------------

    roiZipName =
        imageID + "_" +
        regionSafe + "_" +
        layerSafe + "_" +
        roiSafe + "_" +
        channel + "_" +
        marker + "_" +
        zGroup + "_ROIs.zip";

    if (punctaCount > 0) {
        roiManager("Save", dirROIs + roiZipName);
    }

    // --------------------------------------------------
    // Save QC overlay image
    // --------------------------------------------------

    selectWindow(maskTitle);

    qcTitle =
        imageID + "_" +
        regionSafe + "_" +
        layerSafe + "_" +
        roiSafe + "_" +
        channel + "_" +
        marker + "_" +
        zGroup + "_QC_overlay";

    run("Duplicate...", "title=[" + qcTitle + "] duplicate");
    selectWindow(qcTitle);

    run("RGB Color");

    if (punctaCount > 0) {
        roiManager("Show All with labels");
    }

    run("Flatten");

    saveAs("Tiff", dirOverlays + qcTitle + ".tif");

    close();

    if (isOpen(maskTitle)) {
        selectWindow(maskTitle);
        close();
    }

    roiManager("Reset");
    run("Clear Results");

    File.append("Counted particles: " + punctaCount, logFile);
    File.append("Density per um^2: " + densityPerUm2, logFile);
    File.append("Density per 100 um^2: " + densityPer100Um2, logFile);
}


// ==================================================
// FUNCTION: getImageIDFromMaskName
// ==================================================

function getImageIDFromMaskName(baseName, channel, marker, zGroup) {

    pattern = "_" + channel + "_" + marker + "_" + zGroup;

    idx = indexOf(baseName, pattern);

    if (idx >= 0) {
        return substring(baseName, 0, idx);
    } else {
        return baseName;
    }
}


// ==================================================
// FUNCTION: removeExtension
// ==================================================

function removeExtension(name) {

    dot = lastIndexOf(name, ".");

    if (dot == -1) {
        return name;
    } else {
        return substring(name, 0, dot);
    }
}